-- 1번
INSERT INTO TB_CLASS_TYPE VALUES('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES('02', '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES('05', '논문지도');

-- 2번
CREATE TABLE TB_학생일반정보
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT);
SELECT * FROM TB_학생일반정보;

-- 3번
DROP TABLE TB_국어국문학과;
CREATE TABLE TB_국어국문학과
AS (SELECT STUDENT_NO AS "학번",
        STUDENT_NAME AS "학생이름",
        EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD')) AS "출생년도",
        PROFESSOR_NAME AS "교수이름"
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과');
SELECT * FROM TB_국어국문학과;

-- 4번
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

-- 5번
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

-- 6번
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);
SELECT * FROM TB_STUDENT;

-- 7번
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = 200501
    AND STUDENT_NO IN (SELECT STUDENT_NO
                       FROM TB_STUDENT
                       WHERE STUDENT_NAME = '김명훈'
    AND DEPARTMENT_NO IN (SELECT DEPARTMENT_NO
                          FROM TB_DEPARTMENT
                          WHERE DEPARTMENT_NAME = '의학과'))
    AND CLASS_NO IN (SELECT CLASS_NO
                     FROM TB_CLASS
                     WHERE CLASS_NAME = '피부생리학');
SELECT * FROM TB_GRADE WHERE STUDENT_NO IN (SELECT STUDENT_NO
                                           FROM TB_STUDENT
                                           WHERE STUDENT_NAME = '김명훈');

-- 8번
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');
SELECT * FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');