-- 1번
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2번
SELECT CONCAT(DEPARTMENT_NAME, CONCAT('의 정원은 ', CONCAT(CAPACITY, '명 입니다.'))) AS "학과별 정원"
FROM TB_DEPARTMENT;
SELECT (DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.') AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '국어국문학과')
    AND ABSENCE_YN = 'Y'
    AND SUBSTR(STUDENT_SSN, 8, 1) IN (2, 4);
    
-- 4번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5번
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;

-- 6번
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7번-------------------------------------------------------
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8번
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9번
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
    AND EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002
    AND STUDENT_ADDRESS LIKE '%전주%';