-- 1번
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2번
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3번
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

-- 4번
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5번
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);

-- 6번
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;

-- 7번
ALTER TABLE TB_CATEGORY DROP CONSTRAINT SYS_C007140;
ALTER TABLE TB_CATEGORY
    ADD CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY(CATEGORY_NAME);
ALTER TABLE TB_CLASS_TYPE DROP CONSTRAINT SYS_C007139;
ALTER TABLE TB_CLASS_TYPE
    ADD CONSTRAINT PK_CLASS_TYPE_NO PRIMARY KEY(CLASS_TYPE_NO);

-- 8번
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
COMMIT;

-- 9번
ALTER TABLE TB_DEPARTMENT
    ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);
    
-- 10번
GRANT CREATE VIEW TO wk;

CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생이름", STUDENT_ADDRESS AS "주소"
    FROM TB_STUDENT;
    
-- 11번
CREATE OR REPLACE VIEW VW_지도면담
AS SELECT STUDENT_NAME AS "학생이름", DEPARTMENT_NAME AS "학과이름", PROFESSOR_NAME AS "지도교수이름"
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO);

-- 12번
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME AS "학과이름", COUNT(*) AS "학생 수"
    FROM TB_DEPARTMENT
    JOIN TB_STUDENT USING (DEPARTMENT_NO)
    GROUP BY DEPARTMENT_NAME;
    
-- 13번
UPDATE VW_학생일반정보
SET 학생이름 = '임병준'
WHERE 학번 = 'A213046';

-- 14번
--뷰테이블 만들 때 WITH READ ONLY;를 붙여서 읽기 전용으로 만들어준다.

-- 15번
SELECT *
FROM TB_GRADE
ORDER BY CLASS_NO;

SELECT CLASS_NO, COUNT(STUDENT_NO)
FROM TB_GRADE
GROUP BY CLASS_NO;

SELECT CLASS_NO AS "과목번호", CLASS_NAME AS "과목이름", COUNT(STUDENT_NO) AS "누적수강생수(명)"
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
GROUP BY CLASS_NO, CLASS_NAME
HAVING SUBSTR(TERM_NO, 1, 4) >= 2005;

SELECT "과목번호", "과목이름", "누적수강생수(명)"
    FROM(SELECT CLASS_NO AS "과목번호", CLASS_NAME AS "과목이름", COUNT(STUDENT_NO) AS "누적수강생수(명)"
         FROM (SELECT *
                FROM TB_GRADE
                WHERE SUBSTR(TERM_NO, 1, 4) >= 2005)
         JOIN TB_CLASS USING (CLASS_NO)
         GROUP BY CLASS_NO, CLASS_NAME
         ORDER BY "누적수강생수(명)" DESC)
    WHERE ROWNUM <= 3;