-- 1번
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY "입학년도";

-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번
SELECT PROFESSOR_NAME "교수이름",
    TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 6),'YYYYMMDD')) / 12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) IN (1, 3)
ORDER BY "나이" ASC;

-- 4번
SELECT SUBSTR(PROFESSOR_NAME, 2) "이름"
FROM TB_PROFESSOR;

-- 5번-------------------------------------------------
SELECT DISTINCT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT, TB_PROFESSOR
WHERE MONTHS_BETWEEN(TRUNC(ENTRANCE_DATE, 'YEAR'), TRUNC(TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 6),'YYYYMMDD'), 'YEAR')) / 12+1 != 19;

-- 6번
SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'DAY') AS "2020년 크리스마스"
FROM DUAL;


-- 7번
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD') -- 1999년, 1949년
FROM DUAL;

SELECT TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD') -- 1999년, 2049년
FROM DUAL;

-- 8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;

-- 9번
SELECT ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

-- 10번
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NO
ORDER BY "학과번호" ASC;

-- 11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12번-----------------------------------------------------------------------
SELECT SUBSTR(STUDENT_SSN, 1, 2) AS "년도", POINT AS "년도 별 평점"
FROM TB_STUDENT
GROUP BY SUBSTR(STUDENT_SSN, 1, 2)
HAVING STUDENT_NO = 'A112113'
ORDER BY "년도";

-- 13번
SELECT DEPARTMENT_NO AS "학과코드명", SUM(DECODE(ABSENCE_YN, 'Y', 1, 'N', 0)) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY "학과코드명" ASC;

-- 14번
SELECT STUDENT_NAME AS "동일이름", COUNT(STUDENT_NO) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NO) > 1;

-- 15번
SELECT NVL(SUBSTR(TERM_NO, 1, 4), ' ') AS "년도",
        NVL(SUBSTR(TERM_NO, 5), ' ') AS "학기",
        ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5));